### PR TITLE
chore(api): add pytest as the test runner

### LINKED ISSUE #16: [API] Integrate pytest to run django tests

### PR DESCRIPTION
**Pull request by Samy-33**
closes #16

### CODE REVIEW

**Review by Aksh-Bansal-dev — CHANGES_REQUESTED** [review]
The commit message should be `test(api): add pytest as the test runner` as this commit does not add any feature. And it is also preferred to use imperative style commit messages.

**Review by garg3133 — APPROVED** [review]
LGTM!

**Comment by Samy-33** [comment]
> The commit message should be `test(api): add pytest as the test runner` as this commit does not add any feature.

`chore` is the better fit for this PR as we are introducing new dependencies and updating configurations.

>  And it is also preferred to use imperative style commit messages.

What do you mean by "_imperative style commit messages_"?

**Comment by Aksh-Bansal-dev** [comment]
> What do you mean by "imperative style commit messages"?

The imperative form of `adds pytest as the test runner` would be `add pytest as the test runner`.

From [git docs](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?h=v2.36.1#n181):
> Describe your changes in imperative mood, e.g. "make xyzzy do frotz" instead of "[This patch] makes xyzzy do frotz" or "[I] changed xyzzy to do frotz", as if you are giving orders to the codebase to change its behavior.

**Comment by Samy-33** [comment]
Thanks for the reference doc @Aksh-Bansal-dev. I have made the requested change.

**Review by Aksh-Bansal-dev — APPROVED** [review]
LGTM

**Pull request merged**
